services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres